services:

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cefic
      MYSQL_USER: cefic_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}

      GENERIC_TIMEZONE: America/Lima
      TZ: America/Lima

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}

      GROQ_API_KEY: ${GROQ_API_KEY}

      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"

      DB_TYPE: mysqldb
      DB_MYSQLDB_HOST: mysql
      DB_MYSQLDB_PORT: 3306
      DB_MYSQLDB_DATABASE: cefic
      DB_MYSQLDB_USER: cefic_user
      DB_MYSQLDB_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - n8n_data:/home/node/.n8n

    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./dashboard:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  n8n_data: